// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:a1b7040a-5129-4c01-ba94-7106372147ef',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'whatsuppsapptest-hosting-mobilehub-1140967522',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd382wmm24zs2vz.cloudfront.net',
    'aws_mobile_analytics_app_id': 'c4a249aa24194cc3b73eef1acdd0a67d',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '9deee8a7-6c6d-4c34-8ac5-465691d1999a',
    'aws_project_name': 'WhatSuppsAppTest',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'whatsuppsapptest-mobilehub-1140967522',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_6FRTUlZgW',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '4i5oh45gvl6dq0clq8jutb5t3s',
}

export default awsmobile;
